server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  security:
#    user:
#      name: user
#      password: 123

mybatis:
  mapper-locations: classpath:/mapper/*.xml
